version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - fmasuhr

  - package-ecosystem: npm
    directory: /lambda
    schedule:
      interval: weekly
    assignees:
      - fmasuhr

  - package-ecosystem: terraform
    directory: /examples/basic
    schedule:
      interval: daily
    assignees:
      - fmasuhr
